### PR TITLE
Add a cancelled event to the date/time picker

### LINKED ISSUE #41: cancel, blur event for nativescript-datetimepicker
i want the cancel,ok,blur,dialog close events for nativescript-datetimepicker

### PR DESCRIPTION
**Pull request by yassilah**
## PR Checklist

- [x ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?
There is no way to know if the user cancelled or confirmed.

## What is the new behavior?
A "cancelled" event is emitted when the return value of the picker is null.

Fixes  #41.

### CODE REVIEW

**Comment by yassilah** [comment]
@cla-bot check

**Comment by elena-p** [comment]
@yassipad, 

Could you review and fix the lint errors - https://travis-ci.org/NativeScript/nativescript-datetimepicker/jobs/575108066?

**Comment by yassilah** [comment]
@cla-bot check

**Comment by tgpetrov** [comment]
Hi @yassipad 
I agree that such event would be useful to determine for sure if a user pressed ok or not. My only concern is that now we would not raise the datePickerClosed (and timePickerClosed) event (as the picker is also closed when the user pressed cancel). Maybe we can leave the datePickerClosed (and timePickerClosed) event as it is and add datePickerCancelled and datePickerConfirmed events to differentiate between the press of OK and cancellation. What do you think?

**Comment by yassilah** [comment]
Hi, 
Yes this could work :) But couldn’t we just emit both events cancel+closed at the same time?

**Comment by tgpetrov** [comment]
Yes, that's exactly what I mean - two events at the same - cancel+close vs confirm+close. Something like:
```
            .then((result: Date) => {
                const args = <EventData>{
                    eventName: DatePickerFieldBase.datePickerCancelledEvent,
                    object: this
                };

                if (result) {
                    this.date = result;
                    args.eventName = DatePickerFieldBase.datePickerConfirmedEvent;
                }
                this.notify(args);

                let closedArgs = <EventData>{
                    eventName: DatePickerFieldBase.datePickerClosedEvent,
                    object: this
                };
                this.notify(closedArgs);
            })
```

**Comment by yassilah** [comment]
Yes, great, should we send the closed event first or after the cancelled/confirmed event?

**Comment by tgpetrov** [comment]
It sounds more logical to me to send the confirm/cancel first and then the close event.

**Comment by elena-p** [comment]
@yassipad, 
Thank you for your pull request and your interest to contribute to the {N} community!
However, there hasn't been any activity on this PR for more than a month and I will close it.
Please, open a new PR when you have handled the comments above.

**Pull request closed without merging**
